### ISSUE TITLE
my kibana API Nothing，Can you tell me how to configure  logtrail?

### ISSUE THREAD

**Issue by firehalt** [sivasamyk/logtrail#126]
my kibana API Nothing，Can you tell me how to configure?
For example, my vents getting indexed in ES，and I configured this way for logtrail

input {
 file {
        path => ["/var/log/messages","/var/log/yum.log"]
        type => "system-syslog"
        start_position => "beginning"
         }
}
#Do not change the contents of filter codec
filter {
  if [type] == "system-syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:hostname} %{DATA:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:syslog_message}" }
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}
output {
  elasticsearch {
    hosts => ["192.168.2.39:9200"] 
	index => "system-syslog-%{+YYYY-MM}"
  }
}

**Comment by sivasamyk** [comment]
I am assuming you are able to index the logs in elasticsearch using the above logstash config. (recommend you to use syslog input as specified in the readme example.) I would recommend you to use the index pattern like 'logstash-%{+YYYY-MM}' so that the default templates are created in elasticsearch. Assuming you have installed logtrail in kibana, shutdown the kibana server. Edit the logtrail.json present at plugins/logtrail dir to reflect the index pattern. Save and start Kibana. If you have logs in ES under this index pattern you should be able to see the logs.

**Comment by sivasamyk** [comment]
Please follow the above instructions to get your logs in logtrail.
