### ISSUE TITLE
Logtrail for 6.1.2 not working

### ISSUE THREAD

**Issue by ppawiggers** [sivasamyk/logtrail#231]
I run ES 6.1.2 (Elastic Cloud) and a self-hosted Kibana (docker.elastic.co/kibana/kibana:6.1.2). When I install Logtrail for 6.1.2, everything seems to go well, but after installation, Logtrail does not show up in the menu and the URL /app/logtrail says "Uknown app logtrail"

Any ideas?

**Comment by sivasamyk** [comment]
@ppawiggers How did you install logtrail inside kibana docker container? Did you create a docker image by extending kibana docker image with custom Dockerfile?

**Comment by ppawiggers** [comment]
No, I ran the kibana-plugin installation command in a running (original Elastic Kibana) container.

**Comment by sivasamyk** [comment]
After installing the plugin you need to restart Kibana. I would recommend you to prepare the custom images with Kibana + login installed. checkout : https://github.com/sivasamyk/logtrail/issues/190#issuecomment-334454074

**Comment by RF77** [comment]
Same here... Seems to expect version 6.1.0 instead of 6.1.2

$ .\bin\kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.2-0.1.25.zip
Attempting to transfer from https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.2-0.1.25.zip
Transferring 1338332 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [6.1.0]; found [6.1.2]"

**Comment by ppawiggers** [comment]
Ok thanks, that seems to do the trick.
