### ISSUE TITLE
Support multiple filter types per index

### ISSUE THREAD

**Issue by sammcj** [sivasamyk/logtrail#303]
By default most deployments of logstash I've seen have a single index logstash-date, the problem here is that LogTrail seems to expect you to create an index for every app or some sort of workaround.

It would be useful to match filters for example based on a program, e.g. if the program is nginx, then apply an nginx log filter, if it's kubes apply a kubes filter, syslog a syslog filter etc... rather than needing an separate index for each.

Please correct me if I'm wrong about how this works.

**Comment by ceeeekay** [comment]
Can't you just type a query in the Logtrail search box?

E.g., `type:syslog` or whatever you've named the field.

**Comment by sammcj** [comment]
It's not a problem with searching, it's a limitation of the Logtrail config file.

In all example configs you're only able to set one set of field mappings per logstash index. For example you might have nginx, kubernetes and syslog type logs in your logstash index, but the config only allows you to pick the field mappings for a single type of logs, e.g - you can't run both:

* https://github.com/sivasamyk/logtrail-config-examples/blob/master/syslog/logtrail.json
and 
* https://github.com/sivasamyk/logtrail-config-examples/blob/master/kubernetes/logtrail.json

On the same logstash index (please correct my if I'm interpreting the config file syntax incorrectly).

**Comment by fpytloun** [comment]
I am experiencing the same limitation. I have indexes split by app but I usually want to query more apps at once to join related logs. It would be great to have multiple logtrail indexes using same es index pattern but different search, field mapping, output format, etc.

In my opinion only change that needs to be done is to add `name` key into config and use that in index pattern selectbox instead of mixing it with elasticsearch index name.

**Comment by fpytloun** [comment]
Something like this: https://github.com/fpytloun/logtrail/commit/68b3d4bcedf6becf7edabba65bcc4985c8b5cb42
