### ISSUE TITLE
Support for Kibana 6.5.4

### ISSUE THREAD

**Issue by gabrielcalderon** [sivasamyk/logtrail#335]
Version 6.5.4 was release recently, could we get a Logtrail release for it? 

Would it be possible to make Logtrail releases independent of Kibana minor version number? Like 6.5.x instead of 6.5.4 ?

**Comment by sivasamyk** [comment]
@gabrielcalderon released https://github.com/sivasamyk/logtrail/releases/download/v0.1.30/logtrail-6.5.4-0.1.30.zip

> Would it be possible to make Logtrail releases independent of Kibana minor version number? Like 6.5.x instead of 6.5.4 ?
Unfortunately, this not possible since Kibana required exact match of kibana and plugin versions

You could follow [these](https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#2-update-kibanaversion-in-logtrail-plugin-archive) steps to upgrade package version in your logtrail installation, if a logtrail release is not available.

**Comment by gabrielcalderon** [comment]
Thanks for the quick response and for the information on manual upgrades. :-)
